// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_layout.tsx";
import * as $4 from "./routes/games.tsx";
import * as $5 from "./routes/games/[gameSlug].tsx";
import * as $6 from "./routes/games/[gameSlug]/actors/[actorKindSlug].tsx";
import * as $7 from "./routes/games/[gameSlug]/actors/[actorKindSlug]/[actorSlug].tsx";
import * as $8 from "./routes/games/[gameSlug]/skills.tsx";
import * as $9 from "./routes/games/[gameSlug]/traits.tsx";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_layout.tsx": $3,
    "./routes/games.tsx": $4,
    "./routes/games/[gameSlug].tsx": $5,
    "./routes/games/[gameSlug]/actors/[actorKindSlug].tsx": $6,
    "./routes/games/[gameSlug]/actors/[actorKindSlug]/[actorSlug].tsx": $7,
    "./routes/games/[gameSlug]/skills.tsx": $8,
    "./routes/games/[gameSlug]/traits.tsx": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
